# Generated by Django 4.0.4 on 2022-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0012_rename_co_course_outcome_rename_po_program_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_outcome',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
