# Generated by Django 4.0.4 on 2022-05-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0013_alter_course_outcome_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_outcome',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
