# Generated by Django 4.0.4 on 2022-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0014_alter_course_outcome_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
