# Generated by Django 4.0.4 on 2022-05-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0015_course_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_outcome',
            name='co_no',
        ),
        migrations.RemoveField(
            model_name='course_outcome',
            name='cog_lvl',
        ),
        migrations.RemoveField(
            model_name='course_outcome',
            name='desc',
        ),
        migrations.AddField(
            model_name='course_outcome',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nbasystem.course'),
        ),
    ]
