# Generated by Django 4.0.4 on 2022-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0016_remove_course_outcome_co_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_outcome',
            name='cg_lvl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course_outcome',
            name='co_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course_outcome',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
