# Generated by Django 4.0.4 on 2022-05-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0017_course_outcome_cg_lvl_course_outcome_co_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Outcome',
        ),
    ]
