# Generated by Django 4.0.4 on 2022-05-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0018_delete_course_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('cg_lvl', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nbasystem.course')),
            ],
        ),
    ]
