# Generated by Django 4.0.4 on 2022-05-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0019_course_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_outcome',
            name='cg_lvl',
        ),
    ]
