# Generated by Django 4.0.4 on 2022-05-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0021_alter_course_outcome_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_Educational_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peo_no', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='program_outcome',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program_specific_outcome',
            name='desc',
            field=models.TextField(),
        ),
    ]
