# Generated by Django 4.0.4 on 2022-05-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0022_program_educational_outcome_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program_Educational_Outcome',
        ),
        migrations.DeleteModel(
            name='Program_Outcome',
        ),
        migrations.DeleteModel(
            name='Program_Specific_Outcome',
        ),
    ]
