# Generated by Django 4.0.4 on 2022-05-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0023_delete_program_educational_outcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_Educational_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peo_no', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program_Specific_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pso_no', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
